name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm install --prefix openclonk-extension
    - run: npm run compile --prefix openclonk-extension
    - run: npm run package --prefix openclonk-extension
#     - run: npm test
#       env:
#         CI: true
